package shu.mike.manage;

public enum MangeInfoField
{
	SERVERNUM,PAGEMAXSIZE,TOTALHITS,SEARCHMAXITEM,DEFAULTCAPACITY,
	RESOURCEMANAGERLOGMAXSIZE,DOWNLOADNAME,EMAILACCOUNTUSERNAME,
	EMAILACCOUNTPASSWORD,EMAILACCOUNTSMTPHOST,LOGINGLOGMAXSIZE
}
